### ISSUE TITLE
Problem with Recipe Routes

### ISSUE THREAD

**Issue by halo123u** [cwarner523/Project2#3]
If I remember correctly, people need to be logged in to use your app. Most of your routes such as the edit routes dont use the require logged in Helper which means i can just type the url and can delete everything .

**Comment by cwarner523** [comment]
That's something I forgot to add, that will be coming shortly!

**Comment by dominic-farquharson** [comment]
Oswaldo could be a malicious hacker in disguise. Make sure you add it ASAP!
